apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: {{ .Release.Name }}-influxdb
spec:
  ports:
  - port: {{ .Values.influx.service.port }}
    protocol: TCP
    targetPort: 8086
  type: {{ .Values.influx.service.type }}
  selector:
    app: influxdb
