apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-client
  name: postgres-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-client
  template:
    metadata:
      labels:
        app: postgres-client
    spec:
      containers:
      - image: postgres:latest
        name: postgres-client
        envFrom:
          - configMapRef:
              name: postgres
#          - secretRef:
#              name: postgres